### ISSUE TITLE
Navigate to next/previous declaration

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#167]
**Is your feature request related to a problem? Please describe.**
Currently navigation is only possible via the tree view and getting to the next/previous declaration of some type (e.g. function) requires to open a few nodes in the tree.

**Describe the solution you'd like**
Buttons to navigate to the next/previous declaration in the selection view.
Navigating should be only between elements of the same type, e.g. param1 to param2...
After the last element of a type has been reached, jump to the first element of the next "parent" type. When the last/first element is selected, somehow show that in the buttons. Instead of of "next/previous" the buttons should show "go to beginning/go to end".

Buttons should be on the bottom left and right.

**Comment by jofaul** [comment]
First/Last element button may be added as well

**Comment by lars-reimann** [comment]
Alternative idea: As part of https://github.com/lars-reimann/api-editor/pull/504 I've added the feature that all elements for which the filter truly applies are shown in bold. Additionally, their ascendants and descendants are still shown to provide context:

![image](https://user-images.githubusercontent.com/2501322/169838267-c4568d51-aea0-4e44-872c-75e2030592ad.png)

Rather than having a button that switches between elements of the same level (i.e. next parameter etc.), I would prefer that the next button goes to the next declaration with a bold name and that the previous button goes to the previous one. If a declaration is selected that is not shown in bold, it should still go to the next bold on in the list (likewise for previous).
