### ISSUE TITLE
Automatisch unused Annotation generieren

### ISSUE THREAD

**Issue by Masara** [lars-reimann/api-editor#433]
### Is your feature request related to a problem? Please describe

Teile von APIs werden oft nie genutzt, also sollen diese Teile identifiziert und entfernt werden. Das von Hand tun ist zu aufwendig, also soll es automatisiert werden.

### Desired solution

Anhand von gegebenem Client-Code der die jeweilige API nutzt ein Python Dict erstellen, die ungenutzte Teile der API enthält. Dieses Dict soll mit dem Dict aus #434 kombinierbar und in eine JSON Datei schreibbar sein.
Unter package-parser steht schon Code der erweitert werden kann.

Code dazu soll in einen neuen Ordner unter package-parser/package-parser/commands/generate-annotations geschrieben werden.

### Additional context (optional)

Unter api-editor/data gibt es den API Code, der zu analysierende Client Code wird uns noch von Lars zur Verfügung gestellt.

Es gibt eine Liste (JSON) von ungenutzten Klassen, zu denen zunächst Annotationen generiert werden können. Es soll Parameter für "Input Pfad" und "Output Pfad" geben.

**Comment by lars-reimann** [comment]
JSON for unused annotations:
```json
{
    "unuseds": {
        "sklearn/sklearn.__check_build/raise_build_error": {
            "target": "sklearn/sklearn.__check_build/raise_build_error"
        }
    }
}
```
