### ISSUE TITLE
Automatisch constant Annotation generieren

### ISSUE THREAD

**Issue by Masara** [lars-reimann/api-editor#434]
### Is your feature request related to a problem? Please describe

Parameter in APIs werden oft immer nur auf einen Wert gesetzt, diese Parameter sollen zu Konstanten gemacht werden. Das von Hand tun ist zu aufwendig, also soll es automatisiert werden.

### Desired solution

Anhand von gegebenem Client-Code der die jeweilige API nutzt ein Python Dict erstellen, welches die Teile der API enthält, welche Konstante Werte besitzen soll mit deren dazugehörigen Werten. Dieses Dict soll mit dem Dict aus #433 kombinierbar und in eine JSON Datei schreibbar sein.
Unter package-parser steht schon Code der verwendet werden kann.

Code dazu soll in einen neuen Ordner unter package-parser/package-parser/commands/generate_annotations geschrieben werden.

### Additional context (optional)

Unter api-editor/data gibt es den API Code, der zu analysierende Client Code wird uns noch von Lars zur Verfügung gestellt.

Es gibt eine Datei in der alle Elemente stehen die nur einen Wert annehmen, dort steht aber nicht was dieser Wert ist. Es gibt auch eine Datei in der steht welcher Wert wie oft verwendet wird. Es ist möglich die erstere Datei zu erweitern, das dort auch der Wert drin steht, oder es werden beide Dateien zusammen ausgewertet.

**Comment by lars-reimann** [comment]
JSON for constant annotations:
```json
{
    "constants": {
        "sklearn/sklearn._config/config_context/assume_finite": {
            "target": "sklearn/sklearn._config/config_context/assume_finite",
            "defaultType": "boolean",
            "defaultValue": true
        },
        "sklearn/sklearn._config/config_context/working_memory": {
            "target": "sklearn/sklearn._config/config_context/working_memory",
            "defaultType": "string",
            "defaultValue": "bla"
        },
        "sklearn/sklearn._config/config_context/print_changed_only": {
            "target": "sklearn/sklearn._config/config_context/print_changed_only",
            "defaultType": "none",
            "defaultValue": null
        },
        "sklearn/sklearn._config/config_context/display": {
            "target": "sklearn/sklearn._config/config_context/display",
            "defaultType": "number",
            "defaultValue": "3"
        }
    }
}
```
