### ISSUE TITLE
Automatisierte Herleitung von Enum Annotations

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#444]
### Is your feature request related to a problem? Please describe

Bisher müssen Annotations von Hand markiert werden.

### Desired solution

Die Analyse der Daten, die in Form der usage.json und api.json Datei gegeben sind, soll daher nun automatisch geschehen und die Enum Annotations sollen als Teil der  annotations.json datei exportiert werden. 

Mehr Informationen zu den Details sind [hier](https://uni-bonn.sciebo.de/apps/onlyoffice/1840735236?filePath=%2Ffor_students%2Fpr%C3%A4sentationen%2Fsprint%201%2FSprint%201%20Kundenpraesentation.pptx.) zu finden.

### Additional context

In der Dokumentation ist in der Mengenschreibweise festgehalten, welche string parameter durch enum parameter ersetzt werden können. Es gibt hier bereits eine Funkton, die die entsprechenden Parameter und die dazugehörigen Mengen an strings herausfiltern und in der api.json gespeichert.

Der Code hierzu ist in package-parser/refined_types/main.py zu finden.

Hierbei soll der Name des enums dem großgeschriebenen Namen des strings parameters  und die Werte des Enums den großgeschrieben Werten entsprechen.
Beispiel:
parameter = "wert" -> Parameter.Wert

### Implementations Informationen

In _generate_annotations.py:
def __get_enum_annotations(usages: UsageStore, api: API) -> dict["enums", dict[str, dict[str, str]]]:
Rückgabetyp siehe Kommentar von Lars.
Der Aufruf soll anschließend den anderen in generate_annotations() beigefügt werden.

**Comment by lars-reimann** [comment]
JSON-Format für erzeugte Annotationen (wie @Constant):
```json5
{
  "enums": {
    "sklearn/sklearn.svm._classes/SVC/__init__/kernel": {
      "target": "sklearn/sklearn.svm._classes/SVC/__init__/kernel",
      "enumName": "SVM_Kernel",
      "pairs": [
        {
          "stringValue": "linear",
          "instanceName": "Linear"
        },
        {
          "stringValue": "poly",
          "instanceName": "Poly"
        },
        {
          "stringValue": "rbf",
          "instanceName": "RBF"
        },
        {
          "stringValue": "sigmoid",
          "instanceName": "Sigmoid"
        },
        {
          "stringValue": "precomputed",
          "instanceName": "Precomputed"
        }
      ]
    }
  }
}

```
