### ISSUE TITLE
Automatisierte Herleitung von Boundary Annotations

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#445]
### Is your feature request related to a problem? Please describe

Bisher müssen Annotations von Hand markiert werden.

### Desired solution

Die Analyse der Daten, die in Form der usage.json und api.json Datei gegeben sind, soll daher nun automatisch geschehen und die Boundary Annotations sollen als Teil der  annotations.json datei exportiert werden. 

Mehr Informationen zu den Details sind [hier](https://uni-bonn.sciebo.de/apps/onlyoffice/1840735236?filePath=%2Ffor_students%2Fpr%C3%A4sentationen%2Fsprint%201%2FSprint%201%20Kundenpraesentation.pptx.) zu finden.

### Additional context

In der Dokumentation ist für bestimmte numerische Parameter der Wertebereich festgehalten. Hier gibt es bereits eine unvollständige Funktion, die die Parameter und die entsprechenden Wertebereiche in der api.json abgespeichert.

Es geht hier zunächst nur darum die bereits vorhanden Daten in die Programmstruktur einuzbetten.

Der Code hierzu ist in package-parser/refined_types/main.py zu finden.

### Implementations Informationen

In _generate_annotations.py:
def __get_boundary_annotations(usages: UsageStore, api: API) -> dict["boundaries", dict[str, dict[str, str]]]:
Rückgabetyp siehe Kommentar von Lars.
Der Aufruf soll anschließend den anderen in generate_annotations() beigefügt werden.

**Comment by lars-reimann** [comment]
JSON-Format für erzeugte Annotationen:

```json5

{
  "boundaries": {
    "sklearn/sklearn.linear_model._coordinate_descent/ElasticNet/__init__/l1_ratio": {
      "target": "sklearn/sklearn.linear_model._coordinate_descent/ElasticNet/__init__/l1_ratio",
      "interval": {
        "isDiscrete": false,
        "lowerIntervalLimit": 0,
        "lowerLimitType": 0, // 0 is <=, 1 is <, 2 is no limit
        "upperIntervalLimit": 1,
        "upperLimitType": 0 // 0 is <=, 1 is <, 2 is no limit

      }
    }
  }
}
