### ISSUE TITLE
Modelklassen für Annotationen

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#450]
Momentan werden Annotationen als Dictionaries, Listen und Tupel festgehalten. Dies verhindert statische Überprüfung des Codes. Außerdem ist das Wissen über die Struktur der Annotationen nur implizit festgehalten.

Stattdessen wäre es gut, jede Annotation als eine Klasse zu modellieren und eine `to_json` Methode zu implementieren, um die Klasse in ein Dictionary umzuwandeln.

Um den Code zu verkürzen, lassen sich außerdem Datenklassen nutzen (https://stackoverflow.com/a/54120624). Dann sind auch die manuellen `to_json` Methoden nicht notwendig bzw. lassen sich als

```py
def to_json(self):
    dataclasses.asdict(self)
```

implementieren.

- [x] #460
- [x] #454
- [x] #455
- [x] #456
- [x] #457
- [x] #458
- [x] #459
- [x] to_json nicht mehr für jede Annotation einzeln aufrufen, Enum das Klassenstruktur momentan ersetzt entfernen

**Comment by jofaul** [comment]
Ich will machen :)

**Comment by jofaul** [comment]
Ich will machen :)
