### ISSUE TITLE
Unterklasse für Boundary Annotations

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#458]
Der Intervall soll auch als Klasse implementiert werden.

**Comment by lars-reimann** [comment]
Es bietet sich an, `lowerLimitType` und `upperLimitType` durch eine Enum-Klasse zu repräsentieren. Etwa so:

```py
enum LimitType(Enum):
    LessThanOrEquals(0)
    LessThan(1)
    Unbounded(2)
```
