### ISSUE TITLE
Package Parser: Explicit representation of parameter types and output as a joined property

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#488]
### Is your feature request related to a problem? Please describe

Parameter  Types are currently added in a crude way and should be properly formatted into a "type" json entry.

### Desired solution

- [x] Add dataclasses for the "type" entry.
- [x] Add a "type" json entry that encapsulates all the different viable parameter types.
- [x] Integration of the parser #486
- [x] This should replace "refined_types". For this to work "get_enum_annotations()" and "get_boundary_annotations()" need to be reworked.

### Additional context (optional)

Types:
NamedType (Basic types like int, float... and classes)
EnumType
BoundaryType
UnionType

```
Example Input:
"union_type": [
"callable",
{"k-means++", "random"}
]


Example Output:
"type": {
    "kind": "union_type",
    "types": [
        {
            "kind": "named_type",
            "name": "callable"
        },
        {
            "kind": "enum_type",
            "values": [
                "k-means++",
                "random"
            ]
        }
    ]
}
```

Example Output BoundaryType:
```
"type": {
    "kind": "BoundaryType",
    "base_type": "float",
    "min": 0.0,
    "max": 0.5,
    "min_inclusive": false,
    "max_inclusive": true
}
```

**Comment by lars-reimann** [comment]
Current format for boundary types in API data:
```json5
"refined_type": {
    "kind": "BoundaryType",
    "base_type": "float",
    "min": 0.0,
    "max": 0.5,
    "min_inclusive": false,
    "max_inclusive": true
}
```

**Comment by Aclrian** [comment]
Currently, BoundaryType won't work if the left boundary is negative. We won't touch the regex string.
