### ISSUE TITLE
Navigate to first/last element of surrounded parents

### ISSUE THREAD

**Issue by Aclrian** [lars-reimann/api-editor#505]
Is blocked by: #167
### Is your feature request related to a problem? Please describe

Right now, you can navigate in the tree view from an element of a parent to the first (or last) element of the previous (or next) parent only when you expand the other parent.

### Desired solution

In addition to #167 new Buttons should be added, that can jump to the first element of the same type from the previous parent and the last element of the same type from the next parent. The buttons should encase the 'previous/next' buttons. An idea for their icons could be '<<' and '>>' or the related media control symbols.

**Comment by lars-reimann** [comment]
This is no longer required due to the changes to #167.
