### ISSUE TITLE
BoundaryType not created if left boundary is negative

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#512]
### Describe the bug

Currently, BoundaryType won't work if the left boundary is negative.

> Examples for the description of the docstring are: 
> 
> * `"Tolerance for singular values computed by svd_solver == 'arpack'.\nMust be of range [-1, infinity].\n\n.. versionadded:: 0.18.0"` 
> * `Damping factor in the range '(-0.5, 1.0)'` 
> * `'max_samples' should be in the interval '(-1.0, 1.0]' `
>
> In all cases BoundaryType.from_string() returns None
(https://github.com/lars-reimann/api-editor/issues/512#issuecomment-1140249221)

### Expected behavior

A correct BoundaryType should be created.

**Comment by lars-reimann** [comment]
@Aclrian @nvollroth @lukarade Can you please provide some examples that don't work?

**Comment by Aclrian** [comment]
Examples for the description of the docstring are:
`"Tolerance for singular values computed by svd_solver == 'arpack'.\nMust be of range [-1, infinity].\n\n.. versionadded:: 0.18.0"`
`Damping factor in the range '(-0.5, 1.0)'`
``max_samples` should be in the interval `(-1.0, 1.0]` `
In all cases BoundaryType.from_string() returns None
