### ISSUE TITLE
Differentiate usages

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#533]
### Is your feature request related to a problem? Please describe

Currently, we treat all usages of an API element the same (and might miss some).

### Desired solution

Differentiate types of usages:
* References in expression
* References in types
* Calls
* Member access
* Implicit usage of default value
* ...

In the usage count store we could store a dictionary of numbers rather than a single number:

```json5
{
  "total": 10,
  "called": 8,
  "referenced": 2
}
```

**Comment by guenterk** [comment]
Why is it a problem, that we treat all usages of an API element the same? In addition, the fact that we might miss some usages is a different issue that is not solved by differentiating usage types. Please clarify the benefit of solving this issue.
