### ISSUE TITLE
Review automatically created annotations and add missing ones for `scikit-learn`

### ISSUE THREAD

**Issue by lars-reimann** [lars-reimann/api-editor#678]
### -[ ] module.name; @"contributer"; number of selected elements; completion status; finished in iteration;

- [x] sklearn.metrics; @lukarade; 227; 100%; 3
- [x] sklearn.preprocessing @Aclrian; 159; 100%; 3
- [x] sklearn.model_selection @DavidTen1; 198; 100%; 5
- [x] sklearn.linear_model @nvollroth; 308; ~100%; / 4
- [x] sklearn.feature_extraction.text @Masara; 93; 100%; 3
- [x] sklearn.ensemble @GideonKoenig; 488; 100%; 5
- [x] sklearn.base @jofaul; 25; 100%; 1
- [x] sklearn.pipeline @jofaul; 46; 100%; 1
- [x] sklearn.decomposition @jofaul; 123; 100%; 2
- [x] sklearn.tree @jofaul; 85; 100%; 3
- [x] sklearn.neighbors @jofaul; 90; 100%; 3
- [x] sklearn.naive_bayes @jofaul; 33; 100%; 3
- [x] sklearn.feature_selection @lukarade; 71; 100%; 4
- [x] sklearn.calibration @Masara; 19; 100%; 3
- [x] sklearn.svm @jofaul; 91; 100%, 3
- [x] sklearn.cluster @Aclrian; 93; 100%; 4
- [x] sklearn.impute @Masara; 43; 100%; 4
- [x] sklearn.utils.* @jofaul; 55; 100%; 3
- [x] sklearn.discriminant_analysis @jofaul; 27; 100%; 4
- [x] sklearn.manifold @Masara; 63; 100%; 4
- [x] sklearn.compose @jofaul; 38; 100%; 4
- [x] sklearn.neural_network @jofaul; 62; 100%; 4
- [x] sklearn.feature_extraction @jofaul; 18; 100%; 4
- [x] sklearn.multiclass @jofaul; 23; 100%, 4
- [x] sklearn.multioutput @jofaul; 21; 100%; 4
- [x] sklearn.random_projection @Masara; 19; 100; 4
- [x] sklearn.mixture @jofaul; 26; 100%; 4
- [x] sklearn.covariance @jofaul; 44; 100%; 4
- [x] sklearn @Masara; 10; 100%; 4
- [x] sklearn.dummy @jofaul; 26; 100%; 4
- [x] sklearn.datasets @Masara; 63; 100%; 4
- [x] sklearn.metrics.pairwise @jofaul; 22; 100%; 4
- [x] sklearn.kernel_ridge @jofaul; 13; 100%; 4
- [x] sklearn.gaussian_process @Masara; 42; 100%; 4
- [x] sklearn.inspection @jofaul; 17; 100%; 4
- [x] sklearn.feature_extraction.image @lukarade; 10; 100%; 4
- [x] sklearn.gaussian_process.kernels @jofaul; 42; 100%; 4
- [x] sklearn.isotonic @lukarade; 10; 100%; 4
- [x] sklearn.cross_decomposition @jofaul; 13; 100%; 4
- [x] sklearn.kernel_approximation @jofaul; 11; 100%; 4
- [x] sklearn.semi_supervised @lukarade; 12; 100%, 4

### Recommended configuration of the GUI

1. Load the API data: `data/api/sklearn__api.json`
2. Load the usage data: `data/usages/sklearn__usage_counts.json`
3. Load the auto-generated annotations: `data/annotations/sklearn__annotations.json`
4. In settings:
    1. Set "Module/Class/Function Sorting" to "Usages (Descending)".
    2. Set "Heatmap Mode" to "Usefulness".
5. Set filter to `is:public usefulness:>0`. There should be 2810 matches.

**Comment by jofaul** [comment]
```
annotations:

klassen:

	description: nur typos, oder offensichtliche fehler

	move: klassifikation/regression in sklearn.classifier/regression.X verschieben (.linear_model zB bei linear_models)
	metric/model für regression/classifier

	rename: bei obigen moves zB das classificator/regressor aus namen entfernen

	remove: prüfen ob autogen remove passt, andere annotationen bei remove sind inkorrekt weil es wird gelöscht
	auch: datasets alle entfernen.

	todo: alles was sonst auffällt aber nicht zu anderen annotationen passt (eher weniger verwenden)
	
funktionen:
	
	description/todo wie bei klassen. eher meiden.
	
	remove: wie oben.
	
	pure: autogen; aber noch nicht vorhanden. ignorieren.
	
	calledAfter: beschreibung sagt "darf nur nach methode x aufgerufen werden" -> calledAfter setzen
	
	group: parameter werden in klasse gruppiert und dann wird statt 20 params eine klasse übergeben. 
	also: zB alles was nichts mit ML zu tun hat (-> KlassenNameOther). oder regularization (forgor, bei klassen konstruktor die meisten min/max dinge) (-> KlassenNameRegularization)
	
parameter:

	attribute: ignorieren
	
	boundary: autogen, aber lange nicht immer. prüfen und oft selber hinzufügen, je nach description (nur konstante grenzen)
	
	constant: autogen, prüfen ob param nur einen wert hat. wenn nicht, bug. wenn nur ein wert, auch bug - annotation hinzufügen (default value beachten)
	
	description: wie oben
	
	enum: autogen, prüfen und beschreibung nach nicht gefundenen enums überprüfen.
	
	optional/required: autogen genau ansehen. balken müssen weit genug entfernt/nah genug aneinander sein. vllt manchmal lars fragen um ein gefühl zu bekommen
	
	rename: vllt bei dummen namen, sonst ignorieren.
	
	generell: verwirrende werte nach bedarf anpassen, rückfrage zu kunde vorher.	
```
