### ISSUE TITLE
No required annotation if no value but only variables were set

### ISSUE THREAD

**Issue by nvollroth** [lars-reimann/api-editor#723]
### URL Hash

#/sklearn/sklearn.linear_model._bayes/ARDRegression/fit/X

### Expected Annotation Type

`@required`

### Expected Annotation Inputs

required

**Comment by lars-reimann** [comment]
This happened since no required annotation were generated for parameters that were required anyway. This behavior was changed in https://github.com/lars-reimann/api-editor/pull/769. Now this element also has the expected `@required` annotation.
