### ISSUE TITLE
Show the reason why an annotation was set

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#724]
### Is your feature request related to a problem?

When there are only variables as most used parameters no annotation is generated.

### Desired solution

Describe and store the reason an annotation was automatically generated.

### Screenshots (optional)

![grafik](https://user-images.githubusercontent.com/84092952/175527857-5bbc7ca7-5949-4495-8f66-30656eaed612.png)

### Additional Context (optional)

#/sklearn/sklearn.metrics._regression/mean_squared_error/y_true

**Comment by lars-reimann** [comment]
More general: Describe and store the reason an annotation was automatically generated.
