### ISSUE TITLE
Missing optional annotation with clear candidate for default

### ISSUE THREAD

**Issue by nvollroth** [lars-reimann/api-editor#729]
### URL Hash

`#/sklearn/sklearn.linear_model._bayes/BayesianRidge/__init__/n_iter`

### Expected Annotation Type

`@optional`

### Expected Annotation Inputs

300

**Comment by lars-reimann** [comment]
This happened since no optional annotation were generated for optional parameters that anyway had the same default value. This behavior was changed in https://github.com/lars-reimann/api-editor/pull/769. Now this element also has the expected `@optional` annotation.
