### ISSUE TITLE
Button that pushes qname to clipboard

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#730]
### Is your feature request related to a problem?

For issue creation, filter creation and similar tasks, it can be annoying to either reconstruct or copy the qname/pname from the url.

### Desired solution

A button in the selection view next to the name of the element, that pushes the qname/pname to the clipboard.

### Possible alternatives (optional)

Maybe the name itself is clickable.

**Comment by lars-reimann** [comment]
Alternative idea: Button to report missing/incorrect auto-generated annotations right from the GUI. It could open the appropriate issue form and pre-fill some of the input fields using URL encoding. I'm not yet sure whether this is possible, however.

**Comment by lars-reimann** [comment]
Seems to be possible quite easily. Here's how the url-hash could be pre-filled:

https://github.com/lars-reimann/api-editor/issues/new?assignees=&labels=bug%2Cmissing+annotation&template=missing_annotation.yml&url-hash=test
