### ISSUE TITLE
Missing a Optional annotaion

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#732]
### URL Hash

#/sklearn/sklearn.metrics._ranking/roc_auc_score/average

### Expected Annotation Type

`@optional`

### Expected Annotation Inputs

n/a

### Suggested Solution (optional)

Maybe the annotaion is not set because the parameter values are listed in an enum.

**Comment by lars-reimann** [comment]
This happened since no optional annotation were generated for optional parameters that anyway had the same default value. This behavior was changed in https://github.com/lars-reimann/api-editor/pull/769. Now this element also has the expected `@optional` annotation.
