### ISSUE TITLE
No optional annotation when mixing variables and values with clear default value

### ISSUE THREAD

**Issue by nvollroth** [lars-reimann/api-editor#739]
### URL Hash

`#/sklearn/sklearn.linear_model._coordinate_descent/ElasticNet/__init__/alpha`

### Expected Annotation Type

`@optional`

### Expected Annotation Inputs

1.0

**Comment by lars-reimann** [comment]
This happened since no optional annotation were generated for optional parameters that anyway had the same default value. This behavior was changed in https://github.com/lars-reimann/api-editor/pull/769. Now this element also has the expected `@optional` annotation.
