### ISSUE TITLE
Wrong required annotation on (0, 1)

### ISSUE THREAD

**Issue by Aclrian** [lars-reimann/api-editor#742]
### URL Hash

#/sklearn/sklearn.preprocessing._data/minmax_scale/feature_range

### Actual Annotation Type

`@required`

### Actual Annotation Inputs

n/a

### Expected Annotation Type

`@optional`

### Expected Annotation Inputs

(0, 1)
or no annotation

### Additional Context (optional)

Usages:
(0, 1): 422
others: <10

**Comment by Aclrian** [comment]
also: #/sklearn/sklearn.preprocessing._data/MinMaxScaler/__init__/feature_range

**Comment by lars-reimann** [comment]
Duplicate of https://github.com/lars-reimann/api-editor/issues/755.
