### ISSUE TITLE
More compact header

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#746]
### Is your feature request related to a problem?

Currently the Interface header is a bit cluttered, which makes it hard to see or find what you are actually looking for.

### Desired solution

Things like the **Generate Adapters** Button or the **Delete All Annotations** Buttons might be moved into the **Files** Menu. The Save and Load Filter Section could be compressed, the amount of matches could be displayed a bit smaller and the length of the filter bar could be increased.

### Possible alternatives (optional)

Maybe you could implement an actual "settings bar", slimming the header even more.

**Comment by lars-reimann** [comment]
> Maybe you could implement an actual "settings bar", slimming the header even more.

That might be done in the desktop app I mentioned yesterday:

![image](https://user-images.githubusercontent.com/2501322/175768276-dfd2ea8c-8b9e-4237-8217-e0570369dad7.png)
