### ISSUE TITLE
Wrong required annotation when mixing None and a variable

### ISSUE THREAD

**Issue by nvollroth** [lars-reimann/api-editor#751]
### URL Hash

#/sklearn/sklearn.linear_model._coordinate_descent/ElasticNet/fit/sample_weight

### Actual Annotation Type

`@required`

### Actual Annotation Inputs

required

### Expected Annotation Type

`@optional`

### Expected Annotation Inputs

None

**Comment by lars-reimann** [comment]
This happened since no required annotation were generated for parameters that were required anyway. This behavior was changed in https://github.com/lars-reimann/api-editor/pull/769. Now this element also has the expected `@required` annotation.
