### ISSUE TITLE
Improvements for missing annotation template

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#756]
### Is your feature request related to a problem?

It is exhausting and time consuming to always set the project and the current sprint for an Issue.

### Desired solution

Project/ sprint presets or options to choose from when creating a new issue.

**Comment by lars-reimann** [comment]
The project is set automatically after a few seconds. Unfortunately, the corresponding action (https://github.com/actions/add-to-project) does not yet offer the ability to set fields on the issue. Moreover, custom workflows on projects are still WIP as well. The only way to implement this would be to use the GraphQL API that GitHub offers. This would be replaced later anyway when other options are available, so it's really worth the effort for now.
