### ISSUE TITLE
Numbers with e notation are not interpreted as numbers in the parameter value distribution chart

### ISSUE THREAD

**Issue by nvollroth** [lars-reimann/api-editor#757]
### Describe the bug

Numbers that replace the tens notation with e are no longer recognized as numbers. In this respect, the bar in the chart is colored gray.

### To Reproduce

1. Go to `#/sklearn/sklearn.linear_model._coordinate_descent/ElasticNetCV/__init__/eps`
2. Consider the distribution graph of the parameter

### Expected behavior

The number should still be interpreted as a number and accordingly color the bar pink.

### Screenshots (optional)

![BugParameterValueDistributionChart](https://user-images.githubusercontent.com/100927440/175549421-979d8409-3c06-4762-9905-17d0f5250d8d.png)

**Comment by lars-reimann** [comment]
Annotations seems to be generated properly. This is just an issue in the GUI.
