### ISSUE TITLE
Wrong required annotation with 'auto' as default type 

### ISSUE THREAD

**Issue by Aclrian** [lars-reimann/api-editor#763]
### URL Hash

`#/sklearn/sklearn.preprocessing._encoders/OneHotEncoder/__init__/categories`

### Actual Annotation Type

`@required`

### Actual Annotation Inputs

n/a

### Expected Annotation Type

`@optional`

### Expected Annotation Inputs

'auto'
or no annotation

**Comment by lars-reimann** [comment]
Fixed by https://github.com/lars-reimann/api-editor/pull/758.
