### ISSUE TITLE
Boundary not added for description "non-negative float"

### ISSUE THREAD

**Issue by jofaul** [lars-reimann/api-editor#765]
### URL Hash

#/sklearn/sklearn.tree._classes/DecisionTreeClassifier/__init__/ccp_alpha

### Expected Annotation Type

`@boundary`

### Expected Annotation Inputs

float value >= 0, no upper limit

### Additional Context (optional)

"non-negative float, default=0.0" was not recognized as boundary

**Comment by lars-reimann** [comment]
I'll close this in favor of https://github.com/lars-reimann/api-editor/issues/836.
