### ISSUE TITLE
Support for Links in the documentation

### ISSUE THREAD

**Issue by Aclrian** [lars-reimann/api-editor#766]
### Is your feature request related to a problem?

It's confusing reading somthing like ":class:`~sklearn.pipeline.Pipeline`".

### Desired solution

Replace ":class:`NAME_TO_CLASS`" with a link to #/PATH/TO/CLASS so that the upper example would lead to the Pipeline class.

**Comment by lars-reimann** [comment]
Duplicate of #95.
