### ISSUE TITLE
Set different boundaries for different datatypes

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#826]
### Is your feature request related to a problem?

Currently it's impossible to define different ranges for a parameter that might contain a integer >0 or an float that's <1.

### Desired solution

Boundaries should be allowed to be stacked, for different datatypes (for different modes, so continuous or discrete).

**Comment by lars-reimann** [comment]
Duplicate of https://github.com/lars-reimann/api-editor/issues/767.
