### ISSUE TITLE
Give suggestions to user if they input the keywords incorrectly in the filter

### ISSUE THREAD

**Issue by DavidTen1** [lars-reimann/api-editor#837]
### Is your feature request related to a problem?

Example:  If you try to insert is:class  and however, for any reason,  is:clss  is written

### Desired solution

There should be a suggestion visible that user write the correct keyword

Examples:
 is:clss or is:claasss
 
Did you mean is:class? 

or

skylarn leads to suggesting skilearn

To be general , ask the user  Did you mean ((correctKeyword/s))? 

Compare the flawed filter inputs with the correct ones.
Have the user get a chance of selecting the latter with a mouseclick.

### Possible alternatives (optional)

Further recommendations are welcome

### Screenshots (optional)

![Screenshot 2022-07-01 at 10-39-38 API Editor](https://user-images.githubusercontent.com/101743941/176858595-f856c80c-68df-49f9-ba24-aca414c5bb1e.png)

**Comment by lars-reimann** [comment]
I'll implement this for fixed filters like `annotation:any` only, since here it's very easy to guess what the user meant.
