### ISSUE TITLE
In an annotation dialogue you can still use the shortcuts ctrl + left/right

### ISSUE THREAD

**Issue by jofaul** [lars-reimann/api-editor#846]
### Is your feature request related to a problem?

When adding an annotation, you can still navigate to the next element with the annotation window open, this can lead to wrongly annotated elements and confusion.

Saving after navigating to a new element will save the annotation for the previously selected element

### Desired solution

Disable navigating

### Screenshots (optional)

<img width="328" alt="image" src="https://user-images.githubusercontent.com/54673768/176868543-5806c32c-c3a6-4a5b-8df2-9e29f3552888.png">

**Comment by lars-reimann** [comment]
Subsumed by #848.
