### ISSUE TITLE
Todo Annotations should not be able to be marked as 'Correct'

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#853]
### Is your feature request related to a problem?

Currently you can mark Todo Annotations as 'Correct' which signals, that this is something that can be left the way it is. But the way Todos are used, that doesn't make much sense.

### Desired solution

Either disable or better hide the 'Correct' Button for Todo Annotations.

### Possible alternatives (optional)

Maybe there needs to be a different annotation, that marks things as "hey, this needs to be changed and doesn't currently work"

**Comment by GideonKoenig** [comment]
Will be solved by #771.

**Comment by lars-reimann** [comment]
I'd consider this a separate issue than #771.

**Comment by lars-reimann** [comment]
Thinking about this a little more I'd close this for a different reason: The todo annotation actually has an effect on the generated wrappers, in that TODO comments are being generated. It is meant to denote further changes that have to happen afterwards. Therefore, it makes sense to be able to mark this as correct. 

Just taking notes about annotation can be solved by a mix of #771 (as you suggested) and particularly #854.
