### ISSUE TITLE
Inconsistent colors in statistics view

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#855]
### Is your feature request related to a problem?

The colors of all charts are differnt, thats not esthetic.

### Desired solution

Select a uniform an consistent color sheme for all charts.

### Screenshots (optional)

![grafik](https://user-images.githubusercontent.com/84092952/176886250-99f711c4-a4bf-4203-9ec9-e5ab79f1a41b.png)
![grafik](https://user-images.githubusercontent.com/84092952/176886460-35757ffa-2a85-4ab0-af14-1897836345d6.png)
![grafik](https://user-images.githubusercontent.com/84092952/176886570-70ee3162-4c4f-4a32-8f7a-f44c0268ab43.png)

**Comment by lars-reimann** [comment]
Might use something like https://primer.style/prism to create a palette.

**Comment by Masara** [comment]
![image](https://user-images.githubusercontent.com/2046129/177964976-688c3367-9362-4b27-bc6f-9a3c1e96fd05.png)

Inconsistency!
