### ISSUE TITLE
Missing Usage Statistic

### ISSUE THREAD

**Issue by GideonKoenig** [lars-reimann/api-editor#934]
### Describe the bug

The parameter "sklearn.ensemble.StackingClassifier.fit.sample_weight" is being used 40 times, with it's default value of None. Yet the statistics for it's usages are not displayed.

Other examples are:
sklearn.ensemble.VotingRegressor.fit.sample_weight (Default Value: None)
sklearn.ensemble.StackingRegressor.fit.sample_weight (Default Value: None)
sklearn.ensemble.IsolationForest.__init__.warm_start (Default Value: False)
sklearn.ensemble.IsolationForest.fit.sample_weight (Default Value: None)
sklearn.ensemble.HistGradientBoostingRegressor.__init__.warm_start (Default Value: False)

An example that is working as it's supposed to:
sklearn.ensemble.StackingRegressor.__init__.passthrough (Default Value: False)
sklearn.ensemble.HistGradientBoostingClassifier.__init__.warm_start (Default Value: False)
sklearn.ensemble.HistGradientBoostingClassifier.__init__.tol (Default Value: 1e-07)

The constant annotation is being set correctly though.

### To Reproduce

Open the api-editor and import the api and usage data for sklearn.
Open "sklearn.ensemble.StackingClassifier.fit.sample_weight".

### Expected behavior

The statistics diagram should be displayed.

### Additional Context (optional)

<details>
    <summary>Minimal Usage Store for `sklearn/sklearn.ensemble._stacking/StackingClassifier/fit/sample_weight`</summary>

```json5
{
    "schemaVersion": 1,
    "module_counts": {
        "sklearn/sklearn.ensemble": 16686
    },
    "class_counts": {
        "sklearn/sklearn.ensemble._stacking/StackingClassifier": 138
    },
    "function_counts": {
        "sklearn/sklearn.ensemble._stacking/StackingClassifier/fit": 40
    },
    "parameter_counts": {},
    "value_counts": {}
}
```
</details>

Beispiel fuer funktionierenden Fall:
<details>
    <summary>Minimal Usage Store for `sklearn/sklearn.ensemble._stacking/StackingRegressor/__init__/passthrough`</summary>

```json5
{
    "schemaVersion": 1,
    "module_counts": {
        "sklearn/sklearn.ensemble": 16686
    },
    "class_counts": {
        "sklearn/sklearn.ensemble._stacking/StackingRegressor": 112
    },
    "function_counts": {
        "sklearn/sklearn.ensemble._stacking/StackingRegressor/__init__": 65
    },
    "parameter_counts": {
        "sklearn/sklearn.ensemble._stacking/StackingRegressor/__init__/passthrough": 2
    },
    "value_counts": {
        "sklearn/sklearn.ensemble._stacking/StackingRegressor/__init__/passthrough": {
            "False": 65
        }
    }
}
```
</details>

**Comment by lars-reimann** [comment]
Well spotted. In this case a histogram should be shown with one bar, indicating that the default value `None` was used 40 times.
