### ISSUE TITLE
Select statistics to be shown in statistics view

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#936]
### Is your feature request related to a problem?

When every statistic is shown, it can be hard to find the one you are interested in.

### Desired solution

Offer the possibility to only show the statistics the user has selected in the options.

### Screenshots (optional)

![grafik](https://user-images.githubusercontent.com/84092952/177953781-788652d3-af71-4a20-a5f7-d7ae865be0e6.png)

**Comment by lars-reimann** [comment]
Somewhat subsumed by #899.
