### ISSUE TITLE
No more than 20 characters per annotation

### ISSUE THREAD

**Issue by DavidTen1** [lars-reimann/api-editor#954]
### Is your feature request related to a problem?

If an annotation is too long, some of its last characters might be inside the buttons that surround it to the right

### Desired solution

Have the annotation input changed to not accept more than 20 chars

**Comment by lars-reimann** [comment]
https://github.com/lars-reimann/api-editor/issues/931 subsumes this issue. We need a more sturdy solution than limiting the number of characters per annotation arbitrarily.
