### ISSUE TITLE
Filter for all annotations

### ISSUE THREAD

**Issue by lukarade** [lars-reimann/api-editor#986]
### Is your feature request related to a problem?

When searching for specific annotations it is only possible to filter for required and optional.

### Desired solution

It should be possible to filter for all annotaions (boundary, enum, remove, move, etc.)

### Screenshots (optional)

![grafik](https://user-images.githubusercontent.com/84092952/178601943-41fb7bf6-2fe8-498d-957e-1e449bbe53e8.png)

**Comment by lars-reimann** [comment]
`is:required` show parameters that don't have a default value in the _original_ API. `is:optional` shows the ones that do.

The annotation filters are a little further down. To show only elements with a boundary annotation, you can use the filter `annotation:@boundary`.
